version: "3"

services:
  app:
    build: .
    container_name: gpauth_client
    ports:
      - '8001:5000'
    depends_on:
      - redis
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
      - TZ=Europe/Moscow

  redis:
      image: redis:latest
      expose:
        - 6379
